apply plugin: 'com.android.application'

android {
    namespace 'com.pvzdemo.game'
    compileSdk 34

    defaultConfig {
        applicationId "com.pvzdemo.game"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0-demo"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
